apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "electron-release-server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "electron-release-server.name" . }}
    helm.sh/chart: {{ include "electron-release-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "electron-release-server.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "electron-release-server.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            - name: NODE_ENV
              value: {{ .Values.deployment.nodeEnv }}
            - name: LOG_LEVEL
              value: {{ .Values.deployment.logLevel }}
            - name: APP_URL
              value: {{ .Values.deployment.app.url }}
            - name: APP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-app
                  key: username
            - name: APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-app
                  key: password
            - name: DB_HOST
              value: {{ .Values.deployment.db.host }}
            - name: DB_PORT
              value: {{ .Values.deployment.db.port }}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db
                  key: passsword
            - name: DB_NAME
              value: {{ .Values.deployment.db.name }}
            - name: TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-api
                  key: tokenSecret
            - name: ASSETS_PATH
              value: {{ .Values.deployment.assetsPath }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
